'use strict';

export const SET_SELECTOR_STATE = 'SET_SELECTOR_STATE';
export const UPDATE_GRAPH_URL = 'UPDATE_GRAPH_URL';
export const FETCH_CURRENT_DATA = 'FETCH_CURRENT_DATA';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const FETCH_STATION_LIST = 'FETCH_STATION_LIST';
export const SWITCH_DATE_SELECT_PAD_STATE = 'SWITCH_DATE_SELECT_PAD_STATE';
export const CHANGE_HISTORICAL_DATE = 'CHANGE_HISTORICAL_DATE';
export const SWITCH_GRAPH_DATE_SELECT_PAD_STATE
  = 'SWITCH_GRAPH_DATE_SELECT_PAD_STATE';
export const CHANGE_GRAPH_START_DATE = 'CHANGE_GRAPH_START_DATE';
export const CHANGE_GRAPH_END_DATE = 'CHANGE_GRAPH_END_DATE';

export const INPUT_ACCOUNT = 'INPUT_ACCOUNT';
export const INPUT_PASSWORD = 'INPUT_PASSWORD';
export const PRESS_SIGN_IN = 'PRESS_SIGN_IN';
export const PRESS_NEED_HELP = 'PRESS_NEED_HELP';
export const IS_SIGNED_IN = 'IS_SIGNED_IN';
